featured_slugs:
- moscow-studio
- kvartira-dubay
- nevskaya-dom
projects_order:
- moscow-studio
- kvartira-dubay
- dom-sinegore
- zhk-arkhitektor
- salok-krasoty-tati
- laki-park-dom
- ns-akadem-pulsar
- kvartal-dekabristov
- nevskaya-dom
- vostochny-vayb
- kedrovy-ns
- kabinet-morozovo
- little-classic
